### ISSUE TITLE
Error with "password" argument when running cattr /setup on kubernetes

### ISSUE THREAD

**Issue by khalid244** [cattr-app/backend-application#44]
I encountered an error when trying to run cattr on my kubernetes system. The error message appears in the /setup API as follows:

The "password" argument does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The \"password\" argument does not exist.

This error seems to be related to the "password" argument, which is not being recognized by the ArrayInput component of Symfony Console. I am unsure how to resolve this issue and would appreciate any assistance.

Steps to reproduce:
    - Apply attached yamls in orders percona then backend then frontend.
    - Try to setup cattr using /setup

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: percona-cattr-deployment
  labels:
    app: percona
spec:
  replicas: 1
  selector:
    matchLabels:
      app: percona
  template:
    metadata:
      labels:
        app: percona
    spec:
      containers:
      - name: percona
        image: percona:latest
        imagePullPolicy: Always
        env:
          - name: MYSQL_DATABASE
            value: cattr
          - name: MYSQL_ROOT_PASSWORD
            value: password
        ports:
          - containerPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cattr-deployment
  labels:
    app: cbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbackend
  template:
    metadata:
      labels:
        app: cbackend
    spec:
      containers:
      - name: backend
        image: registry.git.amazingcat.net/cattr/core/cattr-backend:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-cattr-deployment
  labels:
    app: cattr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cattr
  template:
    metadata:
      labels:
        app: cattr
    spec:
      containers:
      - name: frontend
        image: registry.git.amazingcat.net/cattr/core/cattr-frontend:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: percona
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: cbackend
  ports:
  - port: 8090
    targetPort: 8090
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cattr
spec:
  selector:
    app: cattr
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
  type: ClusterIP
```

If anyone knows how I can setup cattr on kubernetes that will be helpful.
@amazing-cat 
@aVyarvelsky 
@sokolovvs 
@constantinebelkin
